ex6_17: cpp/ex6_17.cpp cpp/getInput.cpp cpp/showOutput.cpp cpp/showOutput2.cpp cpp/toLowerCase.cpp cpp/containsCapitals.cpp
	g++ -o ex6_17 cpp/ex6_17.cpp cpp/getInput.cpp cpp/showOutput.cpp cpp/showOutput2.cpp cpp/toLowerCase.cpp cpp/containsCapitals.cpp -std=c++11
