WindowManagerDriver: cpp/WindowManagerDriver.cpp ../screen/cpp/Screen.cpp ../Window_mgr/cpp/Window_mgr.cpp
	g++ cpp/WindowManagerDriver.cpp ../screen/cpp/Screen.cpp ../Window_mgr/cpp/Window_mgr.cpp -std=c++11
